services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: classroom
      POSTGRES_USER: classroom
      POSTGRES_PASSWORD: classroom
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://classroom:classroom@db:5432/classroom
      ORIGINS: http://localhost:5173,http://frontend:5173
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata:
